name: Update GitHub Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          username: zyadbk255
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout gh-pages
        uses: actions/checkout@v5
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy Stats
        run: |
          cp "$GITHUB_WORKSPACE/stats.svg" "$GITHUB_WORKSPACE/gh-pages/stats.svg"
          cp "$GITHUB_WORKSPACE/top-langs.svg" "$GITHUB_WORKSPACE/gh-pages/top-langs.svg"

      - name: Push to gh-pages
        working-directory: gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add stats.svg top-langs.svg
          git commit -m "Update GitHub stats" || echo "No changes"
          git push origin gh-pages
